name: ONNX Runtime Build

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release_onnx:
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker buildx build \
            --cache-from type=local,src=/var/lib/docker/buildx-cache \
            --cache-to type=local,dest=/var/lib/docker/buildx-cache,mode=max \
            -f build/Dockerfile.onnxruntime \
            --output type=local,dest=out/ .

          for filename in out/*.whl; do
            [ -e "$filename" ] || continue
            gh release upload ${{github.event.release.tag_name}} "$filename"
          done
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
